const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES: "categories/SET_CATEGORIES",
  FETCH_CATEGORIES_SATRT: "categories/FETCH_CATEGORIES_SATRT",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
};

export default CATEGORIES_ACTION_TYPES;
